  [phases.setup]
    nixPkgs = [
      "google-chrome",
      "nss",
      "atk",
      "at-spi2-atk",
      "cups",
      "gtk3",
      "pango",
      "libxcomposite",
      "libxdamage",
      "libxrandr",
      "libxkbcommon",
      "libxshmfence"
    ]
